### ISSUE TITLE
Adminlte

### ISSUE THREAD

**Issue by sysrex** [openduty/openduty#13]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by catalincoroeanu** [comment]
- [x] Setup FrontEnd specific work flow: Gulpfile, src files to be compiled, etc

**Comment by catalincoroeanu** [comment]
This is covered inside #30 

Once merged can be closed

**Comment by catalincoroeanu** [comment]
I think this one can be closed no
