### ISSUE TITLE
For development purpose create a script to generate dummy data

### ISSUE THREAD

**Issue by sysrex** [openduty/openduty#14]
Create a script that will generate some dummy data for development purposes

**Comment by catalincoroeanu** [comment]
@sysrex 

this can be achieved easily with Django. I create a `fixture` (this is how is called) and you can import this data very easy like you would start the development server:

`python manage.py loaddata mydata.json`


https://docs.djangoproject.com/en/2.1/ref/django-admin/#loaddata

**Comment by catalincoroeanu** [comment]
this is covered inside `PR Several Fixes` #19
Can be closed I think.
