### ISSUE TITLE
cannot select escalation policy for service

### ISSUE THREAD

**Issue by luto** [openduty/openduty#24]
Glad to see that this project is gaining some traction again! I tried to set it up and create a basic config.

1. create an Escalation Policy
2. create a service
3. expect to be able to select policy created earlier, but the list is empty

This seems to be due to there being two `SchedulePolicy` models: `policies.SchedulePolicy` and `schedules.SchedulePolicy`. The code looks pretty much identical to me, so I guess this is in the middle of some restructuring? It is not quite clear to me which one is the current one.

**Comment by catalincoroeanu** [comment]
@luto 
Thanks for the heads up .

Yes, you are correct. The project is currently under a refactoring process.

I will look into it and try to reproduce it.

**Comment by catalincoroeanu** [comment]
The FIX for this is included into #21 , and is already merged.

can be closed

**Comment by luto** [comment]
works now. Thanks!
