### ISSUE TITLE
openduty requires Twilio of version >=0af4776a961a5b0fef8052082fb1f4027cff172e

### ISSUE THREAD

**Issue by truekonrads** [openduty/openduty#25]
Hi,

openduty won't run if twilio plugin is not at least greater than 0af4776a961a5b0fef8052082fb1f4027cff172e commit of tiwlio.

**Comment by catalincoroeanu** [comment]
@truekonrads 
Acknowledged that.

We will address it ASAP.

**Comment by catalincoroeanu** [comment]
django-twilio: "version": "==0.9.3"
twilio: "version": "==6.20.0"


this can be closed now
